# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Join' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Join
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging' 
  pod 'KakaoSDKAuth', '~> 2.11.3' # 카카오 로그인
  pod 'KakaoSDKUser', '~> 2.11.3' # 사용자 관리
  pod 'Kingfisher', '~> 7.0'
  pod 'Moya/RxSwift', '~> 14.0'
  pod 'ReactorKit', '~> 2.1.1'
  pod 'RxCocoa', '~> 5.0'
  pod 'RxGesture'
  pod 'RxKeyboard'
  pod 'SnapKit', '~> 5.0.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SwiftKeychainWrapper', '~> 4.0.1'
  pod 'Then', '~> 2.7.0'

end
